title: MrWooo
short_description: This is Solid State
description: >- # this means to ignore newlines until "baseurl:"
  Another free + fully responsive site template by <a href="http://html5up.net">HTML5 UP</a> and packaged for Jekyll by <a href="https://www.mrwooo.com">MrWooo</a>
baseurl: "/"

# google services
ganalytics: UA-122812748-2
gtagmanager:
gmapsapikey:

# facebook
fpixel:

# collections
collections:
  main:
    output: true
    permalink: /main/:name

  defaults:
  - scope:
      path: 'assets/images'
      type: 'main'
  values:
    image: true

# contacts
address:
phone:
email: hello@mrwooo.com
  
# social
twitter:
facebook:
instagram:
linkedin:
youtube:
googleplus:
github: https://github.com/dleone81
dribbble:

# copyright
owner: MrWooo.com
